{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b76a72a4",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# ---------- Data ----------\n",
    "data1 = {\n",
    "    'Student_ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],\n",
    "    'Math': [85, 90, 78, 92, 88, 95, 89, 79, 83, 91],\n",
    "    'English': [78, 85, 88, 80, 92, 87, 90, 84, 79, 88],\n",
    "    'Science': [90, 92, 85, 88, 94, 79, 83, 91, 87, 89]\n",
    "}\n",
    "\n",
    "df1 = pd.DataFrame(data1)\n",
    "\n",
    "# ---------- Exercise 1: Average grade per student ----------\n",
    "df1[\"Average\"] = df1[[\"Math\", \"English\", \"Science\"]].mean(axis=1)\n",
    "print(\"Average grade for each student:\")\n",
    "print(df1[[\"Student_ID\", \"Average\"]], \"\\n\")\n",
    "\n",
    "# ---------- Exercise 2: Student with highest average ----------\n",
    "top_student = df1.loc[df1[\"Average\"].idxmax()]\n",
    "print(\"Student with highest average grade:\")\n",
    "print(top_student, \"\\n\")\n",
    "\n",
    "# ---------- Exercise 3: Add 'Total' column ----------\n",
    "df1[\"Total\"] = df1[[\"Math\", \"English\", \"Science\"]].sum(axis=1)\n",
    "print(\"DataFrame with Total column:\")\n",
    "print(df1, \"\\n\")\n",
    "\n",
    "# ---------- Exercise 4: Bar chart for average grades in each subject ----------\n",
    "subject_averages = df1[[\"Math\", \"English\", \"Science\"]].mean()\n",
    "print(\"Average grades per subject:\")\n",
    "print(subject_averages, \"\\n\")\n",
    "\n",
    "subject_averages.plot(kind=\"bar\", color=[\"#4caf50\", \"#2196f3\", \"#ff9800\"])\n",
    "plt.title(\"Average Grades in Each Subject\")\n",
    "plt.ylabel(\"Average Score\")\n",
    "plt.xlabel(\"Subject\")\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ea5cf3cf",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# ---------- Data ----------\n",
    "data2 = {\n",
    "    'Date': pd.date_range(start='2023-01-01', periods=10),\n",
    "    'Product_A': [120, 150, 130, 110, 140, 160, 135, 125, 145, 155],\n",
    "    'Product_B': [90, 110, 100, 80, 95, 105, 98, 88, 102, 112],\n",
    "    'Product_C': [75, 80, 85, 70, 88, 92, 78, 82, 87, 90]\n",
    "}\n",
    "\n",
    "df2 = pd.DataFrame(data2)\n",
    "\n",
    "# ---------- Exercise 1: Total sales per product ----------\n",
    "total_sales = df2[[\"Product_A\", \"Product_B\", \"Product_C\"]].sum()\n",
    "print(\"Total sales for each product:\")\n",
    "print(total_sales, \"\\n\")\n",
    "\n",
    "# ---------- Exercise 2: Date with highest total sales ----------\n",
    "df2[\"Total\"] = df2[[\"Product_A\", \"Product_B\", \"Product_C\"]].sum(axis=1)\n",
    "highest_sales_date = df2.loc[df2[\"Total\"].idxmax(), \"Date\"]\n",
    "print(\"Date with highest total sales:\", highest_sales_date, \"\\n\")\n",
    "\n",
    "# ---------- Exercise 3: Percentage change in sales ----------\n",
    "pct_change = df2[[\"Product_A\", \"Product_B\", \"Product_C\"]].pct_change() * 100\n",
    "print(\"Percentage change in sales from previous day:\")\n",
    "print(pct_change, \"\\n\")\n",
    "\n",
    "# ---------- Exercise 4: Line chart for sales trends ----------\n",
    "plt.figure(figsize=(10, 6))\n",
    "for product in [\"Product_A\", \"Product_B\", \"Product_C\"]:\n",
    "    plt.plot(df2[\"Date\"], df2[product], marker=\"o\", label=product)\n",
    "\n",
    "plt.title(\"Sales Trends Over Time\")\n",
    "plt.xlabel(\"Date\")\n",
    "plt.ylabel(\"Sales\")\n",
    "plt.legend()\n",
    "plt.grid(True)\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "937017e5",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# ---------- Data ----------\n",
    "data3 = {\n",
    "    'Employee_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],\n",
    "    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Hank', 'Ivy', 'Jack'],\n",
    "    'Department': ['HR', 'IT', 'Marketing', 'IT', 'Finance', 'HR', 'Marketing', 'IT', 'Finance', 'Marketing'],\n",
    "    'Salary': [60000, 75000, 65000, 80000, 70000, 72000, 68000, 78000, 69000, 76000],\n",
    "    'Experience (Years)': [3, 5, 2, 8, 4, 6, 3, 7, 2, 5]\n",
    "}\n",
    "\n",
    "df3 = pd.DataFrame(data3)\n",
    "\n",
    "# ---------- Exercise 1: Average salary per department ----------\n",
    "avg_salary = df3.groupby(\"Department\")[\"Salary\"].mean()\n",
    "print(\"Average salary per department:\")\n",
    "print(avg_salary, \"\\n\")\n",
    "\n",
    "# ---------- Exercise 2: Employee with the most experience ----------\n",
    "most_experienced = df3.loc[df3[\"Experience (Years)\"].idxmax()]\n",
    "print(\"Employee with most experience:\")\n",
    "print(most_experienced, \"\\n\")\n",
    "\n",
    "# ---------- Exercise 3: Salary Increase from minimum salary ----------\n",
    "min_salary = df3[\"Salary\"].min()\n",
    "df3[\"Salary Increase (%)\"] = ((df3[\"Salary\"] - min_salary) / min_salary) * 100\n",
    "print(\"DataFrame with Salary Increase column:\")\n",
    "print(df3, \"\\n\")\n",
    "\n",
    "# ---------- Exercise 4: Bar chart - Employee distribution by department ----------\n",
    "dept_count = df3[\"Department\"].value_counts()\n",
    "\n",
    "plt.figure(figsize=(8, 6))\n",
    "dept_count.plot(kind=\"bar\", color=\"skyblue\", edgecolor=\"black\")\n",
    "plt.title(\"Employee Distribution by Department\")\n",
    "plt.xlabel(\"Department\")\n",
    "plt.ylabel(\"Number of Employees\")\n",
    "plt.xticks(rotation=45)\n",
    "plt.grid(axis=\"y\", linestyle=\"--\", alpha=0.7)\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d89aa57a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# ---------- Data ----------\n",
    "data4 = {\n",
    "    'Order_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],\n",
    "    'Customer_ID': [201, 202, 203, 204, 205, 206, 207, 208, 209, 210],\n",
    "    'Product': ['A', 'B', 'A', 'C', 'B', 'C', 'A', 'C', 'B', 'A'],\n",
    "    'Quantity': [2, 3, 1, 4, 2, 3, 2, 5, 1, 3],\n",
    "    'Total_Price': [120, 180, 60, 240, 160, 270, 140, 300, 90, 180]\n",
    "}\n",
    "\n",
    "df4 = pd.DataFrame(data4)\n",
    "\n",
    "# ---------- Exercise 1: Total revenue ----------\n",
    "total_revenue = df4[\"Total_Price\"].sum()\n",
    "print(\"Total revenue from all orders:\", total_revenue, \"\\n\")\n",
    "\n",
    "# ---------- Exercise 2: Most ordered product ----------\n",
    "most_ordered = df4.groupby(\"Product\")[\"Quantity\"].sum().idxmax()\n",
    "print(\"Most ordered product:\", most_ordered, \"\\n\")\n",
    "\n",
    "# ---------- Exercise 3: Average quantity ----------\n",
    "avg_quantity = df4[\"Quantity\"].mean()\n",
    "print(\"Average quantity of products ordered:\", avg_quantity, \"\\n\")\n",
    "\n",
    "# ---------- Exercise 4: Pie chart - Sales distribution ----------\n",
    "sales_by_product = df4.groupby(\"Product\")[\"Total_Price\"].sum()\n",
    "\n",
    "plt.figure(figsize=(6, 6))\n",
    "sales_by_product.plot(\n",
    "    kind=\"pie\",\n",
    "    autopct=\"%.1f%%\",\n",
    "    startangle=90,\n",
    "    colors=[\"#66b3ff\", \"#99ff99\", \"#ff9999\"],\n",
    "    explode=(0.05, 0.05, 0.05)\n",
    ")\n",
    "plt.title(\"Sales Distribution by Product\")\n",
    "plt.ylabel(\"\")  # убрать подпись оси Y\n",
    "plt.show()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
